### ISSUE TITLE
question about '3dkeypoints'.

### ISSUE THREAD

**Issue by Senwang98** [zongdai/AutoShape#3]
Hi, @zongdai 
I have question about 3dkeypoints. Do we need to modify the 3dkeypoints in your json files? (that is to say, 3dkeypoints in the same coordinate system with original kitti official coordinate system?)

**Comment by zongdai** [comment]
Hi, the coordinates of 3dkeypoints in json files are vehicle models center. If we want global coordinate,  we can move 3dkeypoints to kitti camera center coordinate system by applying corresponding rotation and translation, which also provided in json files.

**Comment by Senwang98** [comment]
Okay, I get it! Thank you for replying.
